name: Automated Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository
        uses: actions/checkout@v3

      - name: Using Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run
        run: |
          python find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
          python find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
          python find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt

      - name: Compare Test_1 result with expected result
        run: diff -u test_data/test1_output.txt test_data/test1_expected.txt

      - name: Compare Test_2 result with expected result
        run: diff -u test_data/test2_output.txt test_data/test2_expected.txt

      - name: Compare Test_3 result with expected result
        run: diff -u test_data/test3_output.txt test_data/test3_expected.txt
