name: Automated Tests
jobs:
  test:
    runs-on: ubuntu-latest
  steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
  - name: Run Tests
        run: |
          python find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
          python find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
          python find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt

      - name: Compare Test 1 Output
        run: diff -u test_data/test1_output.txt test_data/test1_expected.txt

      - name: Compare Test 2 Output
        run: diff -u test_data/test2_output.txt test_data/test2_expected.txt

      - name: Compare Test 3 Output
        run: diff -u test_data/test3_output.txt test_data/test3_expected.txt
